# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Anonblog
tagline:          'A Jekyll theme'
description:      'Contiue at your own peril'
url:              
baseurl:          /

author:
  name:           'Anon'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

plugins:     [jekyll-paginate, jekyll-gist]
